

#      - export PACKAGENAME=`cat setup.py | grep -P "^[ ]{4}name=" | cut -d'=' -f2 | sed s/[\',]//g`
#      - pip3 install -e . --extra-index-url https://pypi.org/simple --index-url https://$PACKAGECLOUD_TOKEN:@packagecloud.io/Coalition/leakdetection/pypi/simple
#      - pip3 install -r test-requirements.txt
#      - pip3 freeze
#      - pytest --showlocals --tb=long -v --cov=$PACKAGENAME --cov-report term-missing tests/
#
#  - name: build
#    image: python:3.8-slim
#    environment:
#      PACKAGECLOUD_TOKEN:
#        from_secret: packagecloud_api_key
#    commands:
#      - apt-get update && apt-get -y install curl
#      - pip3 freeze
#      - pip3 install -e . --extra-index-url https://pypi.org/simple --index-url https://$PACKAGECLOUD_TOKEN:@packagecloud.io/Coalition/leakdetection/pypi/simple
#      - python3 setup.py bdist_wheel
#      - curl -X POST https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/Coalition/leakdetection/packages.json -F "package[distro_version_id]=166" -F "package[package_file]=@`ls dist/*.whl`"

---
name: Test, Build, and Upload
on:
  push:
    branches:
      - master
      - main
jobs:
  testing:
    runs-on: ubuntu-20.04
    env:
      PYTHONPATH: content_analyzer
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get -y install python3.8 python3-pip
      - name: Install Python requirements with pip
        run: sudo pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - name: Install Python test requirements with pip
        run: sudo pip3 install -r $GITHUB_WORKSPACE/test-requirements.txt
      - name: Install remaining dependencies
        run: sudo pip3 install -e $GITHUB_WORKSPACE/. --extra-index-url https://pypi.org/simple --index-url https://${{ secrets.LD_PACKAGECLOUD_TOKEN }}:@packagecloud.io/Coalition/leakdetection/pypi/simple
      - name: Export package name
        run: export PACKAGENAME=$(grep name setup.py|cut -d\' -f2)
      - name: Run tests
        run: pytest --showlocals --tb=long -v --cov=$PACKAGENAME --cov-report term-missing $GITHUB_WORKSPACE/tests/
  build:
    needs: testing
    runs-on: ubuntu-20.04
    env:
      PYTHONPATH: content_analyzer
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get -y install python3.8 python3-pip
      - name: Install Python requirements with pip
        run: sudo pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - name: Install PackageCloud Dependencies
        run: sudo pip3 install -e $GITHUB_WORKSPACE/. --extra-index-url https://pypi.org/simple --index-url https://${{ secrets.LD_PACKAGECLOUD_TOKEN }}:@packagecloud.io/Coalition/leakdetection/pypi/simple
      - name: Build packages
        run: python3 setup.py bdist_wheel
      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          cache-name: content_analyzer
        with:
          path: dist/
          key: content_analyzer

  upload:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Install upload dependencies
        run: sudo apt-get update && sudo apt-get -y install curl
      - name: Restore artifacts
        uses: actions/cache@v2
        env:
          cache-name: content_analyzer
        with:
          path: dist/
          key: content_analyzer
      - name: List artifacts
        run: ls -lah dist/
      - name: Upload artifacts to PackageCloud
        run: |
          for i in $(ls dist/*.whl)
          do
            echo $i
            curl -X POST https://${{ secrets.LD_PACKAGECLOUD_TOKEN }}:@packagecloud.io/api/v1/repos/Coalition/leakdetection/packages.json -F "package[distro_version_id]=166" -F "package[package_file]=dist/$i"
          done
